### ISSUE TITLE
Improve Image Sharing

### ISSUE THREAD

**Issue by ys1382** [ClearKeep/ck-ios#203]
Support standard image edit features like crop, flip, doodle.

Text color for “Albums” is red.  “Cancel” should be in red since that’s the warning label.

<img width="197" alt="image" src="https://user-images.githubusercontent.com/1097496/210299736-345768e4-1980-4222-a66d-a4fd203213b6.png">

It is difficult to navigate through images once “Albums” is selected.  Only 2 images can be seen in each row which are sorted in a chronological order. Selecting via gallery would be more convenient.

**Comment by EddieLukeAtmey** [comment]
For now, I'll change the text colors to the usual ones:
- cancel is bold blue, not red, since it's not destructive (delete/remove)
- others are normal blue)

About the selection UX of albums, there is a lot of room to improve it and we'll discuss what's best for our app later. Let's just keep it as it is now.
